URL_MIN_LEN = 1
URL_MAX_LEN = 128
SHORT_MIN_LEN = 1
SHORT_MAX_LEN = 16
ID_DEFAULT_LENGTH = 6

SHORT_ID_REGEX = r'^[a-zA-Z0-9]+$'

FILES_PREFIX = 'files'
RESERVED_SHORT_ID_PREFIXES = {
    FILES_PREFIX,
}
